version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    working_directory: ~/example-ruby-circle # directory where steps will run
    docker: # run the steps with Docker
      - image: circleci/ruby:2.4.1-node-browsers
      
    steps: # a collection of executable commands 
      - checkout      
      - run: ruby -version
      - run: bash <(curl -s https://scripts.scantist.com/staging/ci-circle-jar.sh)
    
